version: '3'

services:

  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
        - '80:80'
        - '81:81'
        - '443:443'
    volumes:
        - ./data/nginx_proxy_manager/data:/data
        - ./data/nginx_proxy_manager/letsencrypt:/etc/letsencrypt
    restart: unless-stopped

  keycloak:
    # internal: keycloak on port 8080
    image: quay.io/keycloak/keycloak:nightly
    command: start
    environment:
        KC_HOSTNAME: 'auth.localhost'
        KC_PROXY: 'edge'
        KEYCLOAK_ADMIN: 'admin'
        KEYCLOAK_ADMIN_PASSWORD: 'admin'
    volumes:
        - ./data/keycloak:/opt/keycloak/data
    restart: unless-stopped

  web: 
    build:
     context: app
     target: builder
    ports: 
      - '8000:8000'
  
  oauth2proxy:
    # internal: oauth2proxy on port 4180
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.6.0
    command: --config /oauth2-proxy.cfg
    volumes:
      - "./oauth2-proxy-keycloak.cfg:/oauth2-proxy.cfg"
    depends_on:
        - keycloak
    restart: unless-stopped